### ISSUE TITLE
How to make conversion with pitch and timbre control?

### ISSUE THREAD

**Issue by SolomidHero** [hhguo/EA-SVC#3]
Hi! Thank you for your great work! I have small question about voice conversion using `inference.py` or model itself in python shell

In the demo (https://hhguo.github.io/DemoEASVC/) there are the best coversions made with pitch shifting. Assume I have a trained model checkpoint. What should I do to produce different conversed audios corresponding to alpha parameter (like in the end of demo: `Pitch Control` section)?

Also, the same question to `Timbre Transfer` section.

I appreciate your help very much!

**Comment by hhguo** [comment]
You can directly change your F0 value to achieve the expected tone. About the timbre transferring, you can interpolate linearly between two speaker encoder outputs (Softmax layer)
